# ワークフロー再利用のテスト
# https://docs.github.com/ja/actions/using-workflows/reusing-workflows


name: Echo Environment Variable

on: 
  workflow_call:
    inputs:
      env_var:
        description: 'Environment variable to echo'
        required: true
        type: string

jobs:
  echo-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_var }}
    steps:
      - uses: Kesin11/actions-timeline@v1

      - name: Echo input environment variable
        run: |
          echo ${{ secrets.TEST_SECRET }}
          echo ${{ inputs.env_var }}
