# This is a basic workflow to help you get started with Actions

name: cache test

# Controls when the workflow will run
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      
      - name: Check and reuse sam resources cache
        uses: actions/cache@v4
        id: resources_cache
        env:
          cache-name: cache-sam-resources
        with:
          path: '**/.aws-sam'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt', 'api/**', 'layer/**') }}

      - name: cache miss
        if: ${{ steps.resources_cache.outputs.cache-hit != 'true' }}
        run: |
          echo 'cache miss'
          mkdir .aws-sam
          touch .aws-sam/cache.txt
          cat ../app/test.txt ./api/test.txt ./layer/test.txt > .aws-sam/cache.txt


      - name: cache hit
        if: ${{ steps.resources_cache.outputs.cache-hit == 'true' }}
        run: |
          echo 'cache hit'
          cat .aws-sam/cache.txt
  
          
          